import * as React from "react";
import { Button, Section, Text } from "react-email";
import { fontStacks, palette } from "./theme";

// Small uppercase label that sits above body headings — same treatment as
// the marketing site's `<span className="text-xs font-medium uppercase
// tracking-[0.18em] text-primary">…</span>` kicker.
export function Kicker({ children }: { children: React.ReactNode }) {
  return (
    <Text
      style={{
        margin: "0 0 12px",
        fontFamily: fontStacks.serif,
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: "0.18em",
        textTransform: "uppercase",
        color: palette.primary,
      }}
    >
      {children}
    </Text>
  );
}

// Body heading. Pairs with `<Italic>` for the in-line italic+primary accent
// the app uses on hero and section headings (e.g. "*generated by AI.*").
export function H1({ children }: { children: React.ReactNode }) {
  return (
    <Text
      style={{
        margin: "0 0 12px",
        fontFamily: fontStacks.serif,
        fontSize: 26,
        lineHeight: 1.2,
        fontWeight: 700,
        letterSpacing: "-0.015em",
        color: palette.foreground,
      }}
    >
      {children}
    </Text>
  );
}

// Italic, primary-tinted accent span. Drop into headings or body copy for
// emphasis — matches `<span className="italic text-primary">…</span>`.
export function Italic({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ fontStyle: "italic", color: palette.primary }}>
      {children}
    </span>
  );
}

// Standard body paragraph. Tighter than the footer microcopy in the layout.
export function Body({
  children,
  marginTop = 14,
}: {
  children: React.ReactNode;
  marginTop?: number;
}) {
  return (
    <Text
      style={{
        margin: `${marginTop}px 0 0`,
        fontFamily: fontStacks.serif,
        fontSize: 15,
        lineHeight: 1.7,
        color: palette.foreground,
      }}
    >
      {children}
    </Text>
  );
}

// Smaller meta paragraph. Used for "this expires in X" / "didn't request
// this?" footnotes that should sit below the main body but above the
// global footer.
export function Meta({ children }: { children: React.ReactNode }) {
  return (
    <Text
      style={{
        margin: "16px 0 0",
        fontFamily: fontStacks.serif,
        fontSize: 13,
        lineHeight: 1.65,
        color: palette.mutedFg,
      }}
    >
      {children}
    </Text>
  );
}

// Cream-on-card callout. Used for "what happens next" blurbs and the
// alpha-invite key panel. Mirrors the app's `bg-card border border-border`
// soft container.
export function Callout({
  children,
  align = "left",
}: {
  children: React.ReactNode;
  align?: "left" | "center";
}) {
  return (
    <Section
      style={{
        marginTop: 24,
        backgroundColor: palette.primaryTint,
        border: `1px solid ${palette.borderSoft}`,
        borderRadius: 12,
        padding: "16px 18px",
        textAlign: align,
      }}
    >
      {children}
    </Section>
  );
}

// Primary CTA button. Camel-tan fill, white text, generous padding — same
// look as the app's `<Button>` default variant on the marketing site.
export function PrimaryButton({
  href,
  children,
}: {
  href: string;
  children: React.ReactNode;
}) {
  return (
    <Section style={{ marginTop: 24, textAlign: "center" }}>
      <Button
        href={href}
        style={{
          display: "inline-block",
          backgroundColor: palette.primary,
          color: palette.primaryFg,
          fontFamily: fontStacks.serif,
          fontSize: 15,
          fontWeight: 700,
          letterSpacing: "0.005em",
          padding: "14px 22px",
          borderRadius: 10,
          textDecoration: "none",
          boxShadow:
            "2px 3px 5px 0 rgba(74, 56, 35, 0.18), 2px 1px 2px -1px rgba(74, 56, 35, 0.18)",
        }}
      >
        {children}
      </Button>
    </Section>
  );
}

// Mono-font code/link block used as a fallback below CTA buttons (so a
// recipient whose mail client mangled the button can still copy the URL)
// and to display the alpha access key.
export function MonoBlock({
  children,
  emphasis = false,
}: {
  children: React.ReactNode;
  emphasis?: boolean;
}) {
  return (
    <Text
      style={{
        margin: "6px 0 0",
        fontFamily: fontStacks.mono,
        fontSize: emphasis ? 18 : 12,
        lineHeight: 1.5,
        letterSpacing: emphasis ? "0.06em" : "normal",
        wordBreak: "break-all",
        fontWeight: emphasis ? 500 : 400,
        color: emphasis ? palette.primary : palette.mutedFg,
      }}
    >
      {children}
    </Text>
  );
}
