import * as React from "react";
import {
  Body,
  Container,
  Head,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Tailwind,
  Text,
} from "react-email";

type Props = {
  preview: string;
  children: React.ReactNode;
};

// Single-source brand chrome (header, footer, type, color tokens) so every
// template stays visually consistent. Templates only own the body content.
export function BrandedLayout({ preview, children }: Props) {
  return (
    <Html lang="en">
      <Head />
      <Preview>{preview}</Preview>
      <Tailwind>
        <Body className="bg-[#f5f5f4] font-sans text-[#171717]">
          <Container className="mx-auto my-10 max-w-[560px] rounded-2xl border border-[#e7e5e4] bg-white p-8 shadow-sm">
            <Section className="pb-2">
              <Text className="m-0 text-2xl font-bold tracking-tight text-[#0a0a0a]">
                Quazom
              </Text>
            </Section>
            <Hr className="my-4 border-[#e7e5e4]" />
            {children}
            <Hr className="my-6 border-[#e7e5e4]" />
            <Section>
              <Text className="m-0 text-xs leading-relaxed text-[#737373]">
                You&rsquo;re getting this email because you signed up for
                Quazom. Questions? Just reply &mdash; a real human will get
                back to you. Or email{" "}
                <Link
                  href="mailto:hello@quazom.ai"
                  className="text-[#737373] underline"
                >
                  hello@quazom.ai
                </Link>
                .
              </Text>
              <Text className="mt-2 mb-0 text-xs text-[#a8a29e]">
                © {new Date().getFullYear()} Quazom &middot; Personal
                curricula, generated by AI.
              </Text>
            </Section>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
