import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@quazom-ai/ui/globals.css";
import { Toaster } from "@quazom-ai/ui/components/ui/sonner";
import { TooltipProvider } from "@quazom-ai/ui/components/ui/tooltip";
import { TRPCReactProvider } from "@/trpc/client";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quazom AI",
  description: "Personal Curricula, Generated by AI.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TRPCReactProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </TRPCReactProvider>
        <Toaster />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
