import Link from "next/link";

const FOOTER_LINKS = [
  { href: "/pricing", label: "Pricing" },
  { href: "/terms", label: "Terms" },
  { href: "/privacy", label: "Privacy" },
] as const;

export function SiteFooter() {
  return (
    <footer className="border-t border-border/60 bg-card/30">
      <div className="mx-auto flex w-full max-w-6xl flex-col items-center justify-between gap-4 px-6 py-8 text-sm text-muted-foreground sm:flex-row">
        <span className="font-heading text-base font-semibold tracking-tight text-foreground">
          Quazom
        </span>
        <nav
          aria-label="Site footer"
          className="flex flex-wrap items-center justify-center gap-x-2 gap-y-1"
        >
          {FOOTER_LINKS.map((link, index) => (
            <span key={link.href} className="inline-flex items-center gap-2">
              {index > 0 ? (
                <span aria-hidden className="text-muted-foreground/40">
                  ·
                </span>
              ) : null}
              <Link
                href={link.href}
                className="transition-colors hover:text-foreground"
              >
                {link.label}
              </Link>
            </span>
          ))}
        </nav>
        <span className="text-center sm:text-right">
          © {new Date().getFullYear()} Quazom. Personal curricula, generated by
          AI.
        </span>
      </div>
    </footer>
  );
}
